name:                fp-lab1
version:             0.1.0.0
github:              "soniina/fp-lab1"

dependencies:
- base >= 4.7 && < 5
- tasty
- tasty-hunit
- containers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  fp-lab1-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fp-lab1
    - tasty
    - tasty-hunit
